import type { Difficulty } from "./types";

export const CATEGORIES = [
  "Développement Web",
  "Science des Données",
  "Gestion de Projet",
  "Leadership & Management",
  "Design & UX",
  "Marketing Digital",
  "Finance & Comptabilité",
  "Ressources Humaines",
  "Communication",
  "Intelligence Artificielle",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  beginner: "Débutant",
  intermediate: "Intermédiaire",
  advanced: "Avancé",
};

export const DIFFICULTY_COLORS: Record<Difficulty, string> = {
  beginner: "bg-primary/10 text-primary",
  intermediate: "bg-accent/10 text-accent",
  advanced: "bg-destructive/10 text-destructive",
};

export const ROLE_LABELS: Record<string, string> = {
  learner: "Apprenant",
  instructor: "Formateur",
  admin: "Administrateur",
  guest: "Invité",
};

export const PRICE_LABELS = {
  free: "Gratuit",
  paid: "Payant",
  all: "Tous",
} as const;

export const SAMPLE_COURSES = [
  {
    id: "1",
    title: "Gestion Avancée de Projets",
    description:
      "Maîtrisez les techniques avancées de gestion de projets complexes et apprenez à coordonner des équipes multidisciplinaires.",
    instructor: "Dr. Amina Benali",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-pm.dim_640x360.jpg",
    category: "Gestion de Projet",
    difficulty: "advanced" as Difficulty,
    duration: 1440,
    lessonCount: 24,
    enrollmentCount: 1247,
    rating: 4.8,
    ratingCount: 312,
    price: 0,
    tags: ["PMP", "Agile", "Scrum"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 65,
  },
  {
    id: "2",
    title: "Fondamentaux de la Science des Données",
    description:
      "De l'analyse exploratoire au machine learning, explorez les bases essentielles pour devenir data scientist.",
    instructor: "Marc Dupont",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-data.dim_640x360.jpg",
    category: "Science des Données",
    difficulty: "beginner" as Difficulty,
    duration: 1800,
    lessonCount: 32,
    enrollmentCount: 2891,
    rating: 4.7,
    ratingCount: 589,
    price: 0,
    tags: ["Python", "Pandas", "ML"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 0,
  },
  {
    id: "3",
    title: "Leadership & Intelligence Émotionnelle",
    description:
      "Développez votre leadership authentique et renforcez votre intelligence émotionnelle pour mieux guider vos équipes.",
    instructor: "Sophie Laurent",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-leadership.dim_640x360.jpg",
    category: "Leadership & Management",
    difficulty: "intermediate" as Difficulty,
    duration: 960,
    lessonCount: 18,
    enrollmentCount: 3102,
    rating: 4.9,
    ratingCount: 748,
    price: 0,
    tags: ["Leadership", "EQ", "Communication"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 30,
  },
  {
    id: "4",
    title: "Marketing Digital Avancé",
    description:
      "Stratégies SEO, réseaux sociaux, publicité en ligne et analytics pour propulser votre présence digitale.",
    instructor: "Karim Mansouri",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-marketing.dim_640x360.jpg",
    category: "Marketing Digital",
    difficulty: "intermediate" as Difficulty,
    duration: 1200,
    lessonCount: 20,
    enrollmentCount: 987,
    rating: 4.6,
    ratingCount: 203,
    price: 0,
    tags: ["SEO", "Social Media", "Analytics"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 0,
  },
  {
    id: "5",
    title: "Design UX/UI Professionnel",
    description:
      "Créez des interfaces utilisateur intuitives et esthétiques avec Figma, les principes du design et les tests utilisateurs.",
    instructor: "Léa Moreau",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-design.dim_640x360.jpg",
    category: "Design & UX",
    difficulty: "beginner" as Difficulty,
    duration: 1560,
    lessonCount: 28,
    enrollmentCount: 1654,
    rating: 4.8,
    ratingCount: 421,
    price: 0,
    tags: ["Figma", "UX", "Prototypage"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 0,
  },
  {
    id: "6",
    title: "Intelligence Artificielle pour Managers",
    description:
      "Comprenez l'IA, ses applications business et comment piloter des projets d'IA dans votre organisation.",
    instructor: "Dr. Thomas Chen",
    instructorAvatar: "",
    thumbnail: "/assets/generated/course-ai.dim_640x360.jpg",
    category: "Intelligence Artificielle",
    difficulty: "beginner" as Difficulty,
    duration: 720,
    lessonCount: 15,
    enrollmentCount: 2103,
    rating: 4.7,
    ratingCount: 367,
    price: 0,
    tags: ["IA", "Stratégie", "Innovation"],
    published: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    progress: 0,
  },
];
