/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIModelConfig {
  'validationModel' : string,
  'structureModel' : string,
  'contentModel' : string,
}
export interface AIStep {
  'completedAt' : [] | [Timestamp],
  'model' : string,
  'output' : [] | [string],
  'step' : bigint,
}
export interface Certificate {
  'id' : CertificateId,
  'ministryReviewerName' : [] | [string],
  'approvedAt' : [] | [Timestamp],
  'isMinistryApproved' : boolean,
  'portfolioPhotoUrl' : [] | [string],
  'resourceCitations' : Array<string>,
  'learnerId' : UserId,
  'learnerName' : string,
  'issuedAt' : Timestamp,
  'courseTitle' : string,
  'qrCodePayload' : string,
  'courseId' : CourseId,
  'instructorName' : string,
}
export type CertificateId = string;
export interface CertificateVerification {
  'issueDate' : Timestamp,
  'courseTitle' : string,
  'isValid' : boolean,
  'ministryApproved' : boolean,
}
export interface CourseGenerationPublic {
  'id' : bigint,
  'status' : GenerationStatus,
  'aiModelConfig' : AIModelConfig,
  'requestDescription' : string,
  'libraryResultsCount' : bigint,
  'createdAt' : Timestamp,
  'errorMessage' : [] | [string],
  'generatedCourseId' : [] | [CourseId],
  'updatedAt' : Timestamp,
  'steps' : Array<AIStep>,
  'resourceIds' : Array<bigint>,
  'requestedBy' : UserId,
}
export type CourseId = bigint;
export interface CourseInput {
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'difficulty' : Difficulty,
  'description' : string,
  'learningOutcomes' : Array<string>,
  'category' : string,
}
export interface CoursePublic {
  'id' : CourseId,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'isPublished' : boolean,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'description' : string,
  'instructorId' : UserId,
  'updatedAt' : Timestamp,
  'learningOutcomes' : Array<string>,
  'category' : string,
}
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Domain {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'requiresManualApproval' : boolean,
  'tier' : DomainTier,
  'description' : string,
}
export type DomainTier = { 'vip' : null } |
  { 'standard' : null };
export interface EnrollmentPublic {
  'completedAt' : [] | [Timestamp],
  'lastLessonId' : [] | [LessonId],
  'lessonProgress' : Array<LessonProgressPublic>,
  'learnerId' : UserId,
  'completionPercent' : bigint,
  'enrolledAt' : Timestamp,
  'courseId' : CourseId,
}
export type ExternalBlob = Uint8Array;
export interface ExternalCoursePublic {
  'id' : string,
  'url' : string,
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'description' : string,
  'platform' : string,
  'viewCount' : bigint,
  'addedAt' : Timestamp,
  'addedBy' : UserId,
}
export type GenerationStatus = { 'step3_gpt4o' : null } |
  { 'step1_deepseek' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'step2_qwen' : null } |
  { 'queued' : null } |
  { 'revision_needed' : null };
export type LessonId = bigint;
export interface LessonInput {
  'title' : string,
  'content' : string,
  'videoBlob' : [] | [ExternalBlob],
  'lessonType' : LessonType,
}
export interface LessonProgressPublic {
  'lessonId' : LessonId,
  'completed' : boolean,
  'quizAttempts' : Array<QuizAttempt>,
  'lastViewedAt' : Timestamp,
}
export interface LessonPublic {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'hasQuiz' : boolean,
  'order' : bigint,
  'createdAt' : Timestamp,
  'videoBlob' : [] | [ExternalBlob],
  'lessonType' : LessonType,
  'courseId' : CourseId,
}
export type LessonType = { 'video' : null } |
  { 'text' : null };
export interface LibrarySearchQuery {
  'domain' : [] | [string],
  'profession' : [] | [string],
  'searchTerm' : string,
  'maxResults' : bigint,
}
export interface LibrarySearchResult {
  'id' : string,
  'url' : string,
  'title' : string,
  'source' : string,
  'previewUrl' : [] | [string],
  'year' : [] | [string],
  'description' : string,
  'author' : string,
  'sourceType' : [] | [string],
  'coverUrl' : [] | [string],
  'videoId' : [] | [string],
}
export interface NotificationPublic {
  'id' : bigint,
  'title' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'courseId' : [] | [CourseId],
}
export type NotificationType = { 'course_update' : null } |
  { 'certificate_issued' : null } |
  { 'quiz_ready' : null } |
  { 'inactivity_reminder' : null } |
  { 'research_feedback' : null };
export interface QuizAttempt {
  'answers' : Array<bigint>,
  'score' : bigint,
  'attemptedAt' : Timestamp,
  'passed' : boolean,
}
export type QuizId = bigint;
export interface QuizPublic {
  'id' : QuizId,
  'lessonId' : LessonId,
  'passingScore' : bigint,
  'questions' : Array<QuizQuestion>,
  'courseId' : CourseId,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'score' : bigint,
  'totalQuestions' : bigint,
  'correctAnswers' : bigint,
  'passed' : boolean,
}
export interface QuizSubmission { 'answers' : Array<bigint>, 'quizId' : QuizId }
export interface ResearchProjectPublic {
  'id' : bigint,
  'status' : ResearchStatus,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'resourceCitations' : Array<string>,
  'updatedAt' : Timestamp,
  'steps' : Array<[ResearchStep, ResearchStepDataPublic]>,
  'currentStep' : ResearchStep,
}
export type ResearchStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'draft' : null };
export type ResearchStep = { 'plan' : null } |
  { 'problematique' : null } |
  { 'hypotheses' : null } |
  { 'sujet' : null } |
  { 'methodologie' : null } |
  { 'redaction' : null };
export interface ResearchStepDataPublic {
  'content' : string,
  'resources' : Array<string>,
  'validated' : boolean,
  'step' : ResearchStep,
  'validatedAt' : [] | [Timestamp],
  'aiResponse' : string,
}
export interface ResourcePublic {
  'id' : bigint,
  'status' : ResourceStatus,
  'title' : string,
  'subjects' : [] | [Array<string>],
  'description' : string,
  'extractedText' : [] | [string],
  'keywords' : [] | [Array<string>],
  'resourceType' : ResourceType,
  'externalUrl' : [] | [string],
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
  'fileUrl' : [] | [string],
}
export type ResourceStatus = { 'pending' : null } |
  { 'error' : null } |
  { 'indexed' : null };
export type ResourceType = { 'pdf' : null } |
  { 'video' : null } |
  { 'html' : null } |
  { 'word' : null } |
  { 'weblink' : null } |
  { 'excel' : null } |
  { 'library_book' : null } |
  { 'youtube' : null } |
  { 'external_course' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TutorMessage {
  'id' : bigint,
  'lessonId' : LessonId,
  'content' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'role' : TutorMessageRole,
  'courseId' : CourseId,
}
export type TutorMessageRole = { 'user' : null } |
  { 'assistant' : null };
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'ministryReviewer' : null } |
  { 'learner' : null } |
  { 'admin' : null } |
  { 'instructor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExternalCourse' : ActorMethod<
    [string, string, string, string, [] | [string]],
    { 'ok' : ExternalCoursePublic } |
      { 'err' : string }
  >,
  'addLesson' : ActorMethod<[CourseId, LessonInput], LessonId>,
  'approveGeneratedCourse' : ActorMethod<
    [bigint, string],
    CourseGenerationPublic
  >,
  'askTutor' : ActorMethod<
    [
      {
        'lessonId' : LessonId,
        'question' : string,
        'lessonContext' : string,
        'courseId' : CourseId,
      },
    ],
    { 'ok' : TutorMessage } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'clearMyNotifications' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearTutorHistory' : ActorMethod<
    [{ 'courseId' : CourseId }],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCourse' : ActorMethod<[CourseInput], CourseId>,
  'createDomain' : ActorMethod<
    [string, DomainTier, string, boolean],
    { 'ok' : Domain } |
      { 'err' : string }
  >,
  'createResearchProject' : ActorMethod<
    [{ 'title' : string }],
    { 'ok' : ResearchProjectPublic } |
      { 'err' : string }
  >,
  'deleteCourse' : ActorMethod<[CourseId], undefined>,
  'deleteDomain' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteExternalCourse' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteLesson' : ActorMethod<[LessonId], undefined>,
  'deleteQuiz' : ActorMethod<[LessonId], undefined>,
  'deleteResource' : ActorMethod<[bigint], undefined>,
  'enrollCourse' : ActorMethod<[CourseId], undefined>,
  'generateCertificate' : ActorMethod<[CourseId], Certificate>,
  'generateChapterQuiz' : ActorMethod<
    [CourseId, LessonId, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateInactivityNotifications' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getAdminModelConfig' : ActorMethod<[], AIModelConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCertificate' : ActorMethod<[CertificateId], [] | [Certificate]>,
  'getCourse' : ActorMethod<[CourseId], [] | [CoursePublic]>,
  'getCourseEnrollments' : ActorMethod<[CourseId], Array<EnrollmentPublic>>,
  'getGenerationStatus' : ActorMethod<[bigint], [] | [CourseGenerationPublic]>,
  'getInstructorCourses' : ActorMethod<[], Array<CoursePublic>>,
  'getLessons' : ActorMethod<[CourseId], Array<LessonPublic>>,
  'getMyCertificates' : ActorMethod<[], Array<Certificate>>,
  'getMyEnrollments' : ActorMethod<[], Array<EnrollmentPublic>>,
  'getMyNotifications' : ActorMethod<
    [{ 'unreadOnly' : boolean }],
    Array<NotificationPublic>
  >,
  'getQuiz' : ActorMethod<[LessonId], [] | [QuizPublic]>,
  'getResearchProject' : ActorMethod<
    [{ 'projectId' : bigint }],
    { 'ok' : ResearchProjectPublic } |
      { 'err' : string }
  >,
  'getResource' : ActorMethod<[bigint], [] | [ResourcePublic]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'importGoogleDocResource' : ActorMethod<
    [string, string, Principal],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'indexResourceText' : ActorMethod<[bigint, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllGenerations' : ActorMethod<[], Array<CourseGenerationPublic>>,
  'listCourses' : ActorMethod<[[] | [string]], Array<CoursePublic>>,
  'listDomains' : ActorMethod<[], Array<Domain>>,
  'listExternalCourses' : ActorMethod<[], Array<ExternalCoursePublic>>,
  'listMyGenerations' : ActorMethod<[], Array<CourseGenerationPublic>>,
  'listMyResearchProjects' : ActorMethod<[], Array<ResearchProjectPublic>>,
  'listResources' : ActorMethod<
    [[] | [ResourceType], [] | [string]],
    Array<ResourcePublic>
  >,
  'markAllNotificationsRead' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markLessonComplete' : ActorMethod<[CourseId, LessonId], undefined>,
  'markNotificationRead' : ActorMethod<
    [{ 'notifId' : bigint }],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'queryTutorHistory' : ActorMethod<
    [{ 'courseId' : CourseId }],
    Array<TutorMessage>
  >,
  'rejectGeneratedCourse' : ActorMethod<
    [bigint, string],
    CourseGenerationPublic
  >,
  'reorderLesson' : ActorMethod<[LessonId, bigint], undefined>,
  'requestCourseGeneration' : ActorMethod<
    [string, [] | [Array<bigint>]],
    CourseGenerationPublic
  >,
  'runAIGeneration' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, UserRole, [] | [string]],
    undefined
  >,
  'saveLastViewedLesson' : ActorMethod<[CourseId, LessonId], undefined>,
  'searchCourses' : ActorMethod<[string, [] | [string]], Array<CoursePublic>>,
  'searchRealLibraries' : ActorMethod<[string, Array<string>], Array<string>>,
  'searchWorldLibraries' : ActorMethod<
    [LibrarySearchQuery],
    Array<LibrarySearchResult>
  >,
  'sendResearchMessage' : ActorMethod<
    [{ 'step' : ResearchStep, 'userInput' : string, 'projectId' : bigint }],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setAdminModelConfig' : ActorMethod<[AIModelConfig], undefined>,
  'setCoursePublished' : ActorMethod<[CourseId, boolean], undefined>,
  'setQuiz' : ActorMethod<[LessonId, Array<QuizQuestion>, bigint], QuizId>,
  'submitQuiz' : ActorMethod<[CourseId, QuizSubmission], QuizResult>,
  'trackExternalCourseView' : ActorMethod<[string], undefined>,
  'transformHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformNotifHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformResearchHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformResourcesHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformTutorHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'unenrollCourse' : ActorMethod<[CourseId], undefined>,
  'updateCourse' : ActorMethod<[CourseId, CourseInput], undefined>,
  'updateDomain' : ActorMethod<
    [bigint, DomainTier, boolean],
    { 'ok' : Domain } |
      { 'err' : string }
  >,
  'updateLesson' : ActorMethod<[LessonId, LessonInput], undefined>,
  'updateResourceMetadata' : ActorMethod<
    [bigint, string, string, [] | [Array<string>], [] | [Array<string>]],
    ResourcePublic
  >,
  'uploadResource' : ActorMethod<
    [
      string,
      string,
      ResourceType,
      [] | [string],
      [] | [string],
      [] | [Array<string>],
    ],
    ResourcePublic
  >,
  'validateResearchStep' : ActorMethod<
    [{ 'step' : ResearchStep, 'projectId' : bigint }],
    { 'ok' : ResearchProjectPublic } |
      { 'err' : string }
  >,
  'verifyCertificateQR' : ActorMethod<[string], [] | [CertificateVerification]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];