/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ExternalCoursePublic = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'viewCount' : IDL.Nat,
  'addedAt' : Timestamp,
  'addedBy' : UserId,
});
export const CourseId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LessonType = IDL.Variant({
  'video' : IDL.Null,
  'text' : IDL.Null,
});
export const LessonInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'lessonType' : LessonType,
});
export const LessonId = IDL.Nat;
export const GenerationStatus = IDL.Variant({
  'step3_gpt4o' : IDL.Null,
  'step1_deepseek' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'step2_qwen' : IDL.Null,
  'queued' : IDL.Null,
  'revision_needed' : IDL.Null,
});
export const AIModelConfig = IDL.Record({
  'validationModel' : IDL.Text,
  'structureModel' : IDL.Text,
  'contentModel' : IDL.Text,
});
export const AIStep = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'model' : IDL.Text,
  'output' : IDL.Opt(IDL.Text),
  'step' : IDL.Nat,
});
export const CourseGenerationPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : GenerationStatus,
  'aiModelConfig' : AIModelConfig,
  'requestDescription' : IDL.Text,
  'libraryResultsCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'errorMessage' : IDL.Opt(IDL.Text),
  'generatedCourseId' : IDL.Opt(CourseId),
  'updatedAt' : Timestamp,
  'steps' : IDL.Vec(AIStep),
  'resourceIds' : IDL.Vec(IDL.Nat),
  'requestedBy' : UserId,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const CourseInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'learningOutcomes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'ministryReviewer' : IDL.Null,
  'learner' : IDL.Null,
  'admin' : IDL.Null,
  'instructor' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
});
export const CertificateId = IDL.Text;
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'ministryReviewerName' : IDL.Opt(IDL.Text),
  'approvedAt' : IDL.Opt(Timestamp),
  'isMinistryApproved' : IDL.Bool,
  'resourceCitations' : IDL.Vec(IDL.Text),
  'learnerId' : UserId,
  'learnerName' : IDL.Text,
  'issuedAt' : Timestamp,
  'courseTitle' : IDL.Text,
  'qrCodePayload' : IDL.Text,
  'courseId' : CourseId,
  'instructorName' : IDL.Text,
});
export const CoursePublic = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'isPublished' : IDL.Bool,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'instructorId' : UserId,
  'updatedAt' : Timestamp,
  'learningOutcomes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const QuizAttempt = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'attemptedAt' : Timestamp,
  'passed' : IDL.Bool,
});
export const LessonProgressPublic = IDL.Record({
  'lessonId' : LessonId,
  'completed' : IDL.Bool,
  'quizAttempts' : IDL.Vec(QuizAttempt),
  'lastViewedAt' : Timestamp,
});
export const EnrollmentPublic = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'lastLessonId' : IDL.Opt(LessonId),
  'lessonProgress' : IDL.Vec(LessonProgressPublic),
  'learnerId' : UserId,
  'completionPercent' : IDL.Nat,
  'enrolledAt' : Timestamp,
  'courseId' : CourseId,
});
export const LessonPublic = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'hasQuiz' : IDL.Bool,
  'order' : IDL.Nat,
  'createdAt' : Timestamp,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'lessonType' : LessonType,
  'courseId' : CourseId,
});
export const QuizId = IDL.Nat;
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const QuizPublic = IDL.Record({
  'id' : QuizId,
  'lessonId' : LessonId,
  'passingScore' : IDL.Nat,
  'questions' : IDL.Vec(QuizQuestion),
  'courseId' : CourseId,
});
export const ResourceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Null,
  'indexed' : IDL.Null,
});
export const ResourceType = IDL.Variant({
  'pdf' : IDL.Null,
  'video' : IDL.Null,
  'html' : IDL.Null,
  'word' : IDL.Null,
  'weblink' : IDL.Null,
  'excel' : IDL.Null,
  'library_book' : IDL.Null,
  'youtube' : IDL.Null,
  'external_course' : IDL.Null,
});
export const ResourcePublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ResourceStatus,
  'title' : IDL.Text,
  'subjects' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Text,
  'extractedText' : IDL.Opt(IDL.Text),
  'keywords' : IDL.Opt(IDL.Vec(IDL.Text)),
  'resourceType' : ResourceType,
  'externalUrl' : IDL.Opt(IDL.Text),
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const LibrarySearchQuery = IDL.Record({
  'domain' : IDL.Opt(IDL.Text),
  'profession' : IDL.Opt(IDL.Text),
  'searchTerm' : IDL.Text,
  'maxResults' : IDL.Nat,
});
export const LibrarySearchResult = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'previewUrl' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Text,
  'coverUrl' : IDL.Opt(IDL.Text),
});
export const QuizSubmission = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'quizId' : QuizId,
});
export const QuizResult = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'passed' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const CertificateVerification = IDL.Record({
  'issueDate' : Timestamp,
  'courseTitle' : IDL.Text,
  'isValid' : IDL.Bool,
  'ministryApproved' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addExternalCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : ExternalCoursePublic, 'err' : IDL.Text })],
      [],
    ),
  'addLesson' : IDL.Func([CourseId, LessonInput], [LessonId], []),
  'approveGeneratedCourse' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [CourseGenerationPublic],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createCourse' : IDL.Func([CourseInput], [CourseId], []),
  'deleteCourse' : IDL.Func([CourseId], [], []),
  'deleteExternalCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteLesson' : IDL.Func([LessonId], [], []),
  'deleteQuiz' : IDL.Func([LessonId], [], []),
  'deleteResource' : IDL.Func([IDL.Nat], [], []),
  'enrollCourse' : IDL.Func([CourseId], [], []),
  'getAdminModelConfig' : IDL.Func([], [AIModelConfig], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCertificate' : IDL.Func(
      [CertificateId],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(CoursePublic)], ['query']),
  'getCourseEnrollments' : IDL.Func(
      [CourseId],
      [IDL.Vec(EnrollmentPublic)],
      ['query'],
    ),
  'getGenerationStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CourseGenerationPublic)],
      ['query'],
    ),
  'getInstructorCourses' : IDL.Func([], [IDL.Vec(CoursePublic)], ['query']),
  'getLessons' : IDL.Func([CourseId], [IDL.Vec(LessonPublic)], ['query']),
  'getMyCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentPublic)], ['query']),
  'getQuiz' : IDL.Func([LessonId], [IDL.Opt(QuizPublic)], ['query']),
  'getResource' : IDL.Func([IDL.Nat], [IDL.Opt(ResourcePublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'indexResourceText' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllGenerations' : IDL.Func(
      [],
      [IDL.Vec(CourseGenerationPublic)],
      ['query'],
    ),
  'listCourses' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(CoursePublic)],
      ['query'],
    ),
  'listExternalCourses' : IDL.Func(
      [],
      [IDL.Vec(ExternalCoursePublic)],
      ['query'],
    ),
  'listMyGenerations' : IDL.Func(
      [],
      [IDL.Vec(CourseGenerationPublic)],
      ['query'],
    ),
  'listResources' : IDL.Func(
      [IDL.Opt(ResourceType), IDL.Opt(IDL.Text)],
      [IDL.Vec(ResourcePublic)],
      ['query'],
    ),
  'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
  'rejectGeneratedCourse' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [CourseGenerationPublic],
      [],
    ),
  'reorderLesson' : IDL.Func([LessonId, IDL.Nat], [], []),
  'requestCourseGeneration' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat))],
      [CourseGenerationPublic],
      [],
    ),
  'runAIGeneration' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'saveLastViewedLesson' : IDL.Func([CourseId, LessonId], [], []),
  'searchCourses' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(CoursePublic)],
      ['query'],
    ),
  'searchWorldLibraries' : IDL.Func(
      [LibrarySearchQuery],
      [IDL.Vec(LibrarySearchResult)],
      [],
    ),
  'setAdminModelConfig' : IDL.Func([AIModelConfig], [], []),
  'setCoursePublished' : IDL.Func([CourseId, IDL.Bool], [], []),
  'setQuiz' : IDL.Func(
      [LessonId, IDL.Vec(QuizQuestion), IDL.Nat],
      [QuizId],
      [],
    ),
  'submitQuiz' : IDL.Func([CourseId, QuizSubmission], [QuizResult], []),
  'trackExternalCourseView' : IDL.Func([IDL.Text], [], []),
  'transformHttpResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unenrollCourse' : IDL.Func([CourseId], [], []),
  'updateCourse' : IDL.Func([CourseId, CourseInput], [], []),
  'updateLesson' : IDL.Func([LessonId, LessonInput], [], []),
  'updateResourceMetadata' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [ResourcePublic],
      [],
    ),
  'uploadResource' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ResourceType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [ResourcePublic],
      [],
    ),
  'verifyCertificateQR' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CertificateVerification)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ExternalCoursePublic = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'viewCount' : IDL.Nat,
    'addedAt' : Timestamp,
    'addedBy' : UserId,
  });
  const CourseId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LessonType = IDL.Variant({ 'video' : IDL.Null, 'text' : IDL.Null });
  const LessonInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'lessonType' : LessonType,
  });
  const LessonId = IDL.Nat;
  const GenerationStatus = IDL.Variant({
    'step3_gpt4o' : IDL.Null,
    'step1_deepseek' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'step2_qwen' : IDL.Null,
    'queued' : IDL.Null,
    'revision_needed' : IDL.Null,
  });
  const AIModelConfig = IDL.Record({
    'validationModel' : IDL.Text,
    'structureModel' : IDL.Text,
    'contentModel' : IDL.Text,
  });
  const AIStep = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'model' : IDL.Text,
    'output' : IDL.Opt(IDL.Text),
    'step' : IDL.Nat,
  });
  const CourseGenerationPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : GenerationStatus,
    'aiModelConfig' : AIModelConfig,
    'requestDescription' : IDL.Text,
    'libraryResultsCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'errorMessage' : IDL.Opt(IDL.Text),
    'generatedCourseId' : IDL.Opt(CourseId),
    'updatedAt' : Timestamp,
    'steps' : IDL.Vec(AIStep),
    'resourceIds' : IDL.Vec(IDL.Nat),
    'requestedBy' : UserId,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const CourseInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'learningOutcomes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'ministryReviewer' : IDL.Null,
    'learner' : IDL.Null,
    'admin' : IDL.Null,
    'instructor' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
  });
  const CertificateId = IDL.Text;
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'ministryReviewerName' : IDL.Opt(IDL.Text),
    'approvedAt' : IDL.Opt(Timestamp),
    'isMinistryApproved' : IDL.Bool,
    'resourceCitations' : IDL.Vec(IDL.Text),
    'learnerId' : UserId,
    'learnerName' : IDL.Text,
    'issuedAt' : Timestamp,
    'courseTitle' : IDL.Text,
    'qrCodePayload' : IDL.Text,
    'courseId' : CourseId,
    'instructorName' : IDL.Text,
  });
  const CoursePublic = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'isPublished' : IDL.Bool,
    'difficulty' : Difficulty,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'instructorId' : UserId,
    'updatedAt' : Timestamp,
    'learningOutcomes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const QuizAttempt = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'attemptedAt' : Timestamp,
    'passed' : IDL.Bool,
  });
  const LessonProgressPublic = IDL.Record({
    'lessonId' : LessonId,
    'completed' : IDL.Bool,
    'quizAttempts' : IDL.Vec(QuizAttempt),
    'lastViewedAt' : Timestamp,
  });
  const EnrollmentPublic = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'lastLessonId' : IDL.Opt(LessonId),
    'lessonProgress' : IDL.Vec(LessonProgressPublic),
    'learnerId' : UserId,
    'completionPercent' : IDL.Nat,
    'enrolledAt' : Timestamp,
    'courseId' : CourseId,
  });
  const LessonPublic = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'hasQuiz' : IDL.Bool,
    'order' : IDL.Nat,
    'createdAt' : Timestamp,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'lessonType' : LessonType,
    'courseId' : CourseId,
  });
  const QuizId = IDL.Nat;
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const QuizPublic = IDL.Record({
    'id' : QuizId,
    'lessonId' : LessonId,
    'passingScore' : IDL.Nat,
    'questions' : IDL.Vec(QuizQuestion),
    'courseId' : CourseId,
  });
  const ResourceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Null,
    'indexed' : IDL.Null,
  });
  const ResourceType = IDL.Variant({
    'pdf' : IDL.Null,
    'video' : IDL.Null,
    'html' : IDL.Null,
    'word' : IDL.Null,
    'weblink' : IDL.Null,
    'excel' : IDL.Null,
    'library_book' : IDL.Null,
    'youtube' : IDL.Null,
    'external_course' : IDL.Null,
  });
  const ResourcePublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ResourceStatus,
    'title' : IDL.Text,
    'subjects' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Text,
    'extractedText' : IDL.Opt(IDL.Text),
    'keywords' : IDL.Opt(IDL.Vec(IDL.Text)),
    'resourceType' : ResourceType,
    'externalUrl' : IDL.Opt(IDL.Text),
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const LibrarySearchQuery = IDL.Record({
    'domain' : IDL.Opt(IDL.Text),
    'profession' : IDL.Opt(IDL.Text),
    'searchTerm' : IDL.Text,
    'maxResults' : IDL.Nat,
  });
  const LibrarySearchResult = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'previewUrl' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Text,
    'coverUrl' : IDL.Opt(IDL.Text),
  });
  const QuizSubmission = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'quizId' : QuizId,
  });
  const QuizResult = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'passed' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const CertificateVerification = IDL.Record({
    'issueDate' : Timestamp,
    'courseTitle' : IDL.Text,
    'isValid' : IDL.Bool,
    'ministryApproved' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addExternalCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : ExternalCoursePublic, 'err' : IDL.Text })],
        [],
      ),
    'addLesson' : IDL.Func([CourseId, LessonInput], [LessonId], []),
    'approveGeneratedCourse' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [CourseGenerationPublic],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createCourse' : IDL.Func([CourseInput], [CourseId], []),
    'deleteCourse' : IDL.Func([CourseId], [], []),
    'deleteExternalCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteLesson' : IDL.Func([LessonId], [], []),
    'deleteQuiz' : IDL.Func([LessonId], [], []),
    'deleteResource' : IDL.Func([IDL.Nat], [], []),
    'enrollCourse' : IDL.Func([CourseId], [], []),
    'getAdminModelConfig' : IDL.Func([], [AIModelConfig], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCertificate' : IDL.Func(
        [CertificateId],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(CoursePublic)], ['query']),
    'getCourseEnrollments' : IDL.Func(
        [CourseId],
        [IDL.Vec(EnrollmentPublic)],
        ['query'],
      ),
    'getGenerationStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CourseGenerationPublic)],
        ['query'],
      ),
    'getInstructorCourses' : IDL.Func([], [IDL.Vec(CoursePublic)], ['query']),
    'getLessons' : IDL.Func([CourseId], [IDL.Vec(LessonPublic)], ['query']),
    'getMyCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentPublic)], ['query']),
    'getQuiz' : IDL.Func([LessonId], [IDL.Opt(QuizPublic)], ['query']),
    'getResource' : IDL.Func([IDL.Nat], [IDL.Opt(ResourcePublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'indexResourceText' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllGenerations' : IDL.Func(
        [],
        [IDL.Vec(CourseGenerationPublic)],
        ['query'],
      ),
    'listCourses' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(CoursePublic)],
        ['query'],
      ),
    'listExternalCourses' : IDL.Func(
        [],
        [IDL.Vec(ExternalCoursePublic)],
        ['query'],
      ),
    'listMyGenerations' : IDL.Func(
        [],
        [IDL.Vec(CourseGenerationPublic)],
        ['query'],
      ),
    'listResources' : IDL.Func(
        [IDL.Opt(ResourceType), IDL.Opt(IDL.Text)],
        [IDL.Vec(ResourcePublic)],
        ['query'],
      ),
    'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
    'rejectGeneratedCourse' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [CourseGenerationPublic],
        [],
      ),
    'reorderLesson' : IDL.Func([LessonId, IDL.Nat], [], []),
    'requestCourseGeneration' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat))],
        [CourseGenerationPublic],
        [],
      ),
    'runAIGeneration' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'saveLastViewedLesson' : IDL.Func([CourseId, LessonId], [], []),
    'searchCourses' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(CoursePublic)],
        ['query'],
      ),
    'searchWorldLibraries' : IDL.Func(
        [LibrarySearchQuery],
        [IDL.Vec(LibrarySearchResult)],
        [],
      ),
    'setAdminModelConfig' : IDL.Func([AIModelConfig], [], []),
    'setCoursePublished' : IDL.Func([CourseId, IDL.Bool], [], []),
    'setQuiz' : IDL.Func(
        [LessonId, IDL.Vec(QuizQuestion), IDL.Nat],
        [QuizId],
        [],
      ),
    'submitQuiz' : IDL.Func([CourseId, QuizSubmission], [QuizResult], []),
    'trackExternalCourseView' : IDL.Func([IDL.Text], [], []),
    'transformHttpResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unenrollCourse' : IDL.Func([CourseId], [], []),
    'updateCourse' : IDL.Func([CourseId, CourseInput], [], []),
    'updateLesson' : IDL.Func([LessonId, LessonInput], [], []),
    'updateResourceMetadata' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [ResourcePublic],
        [],
      ),
    'uploadResource' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ResourceType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [ResourcePublic],
        [],
      ),
    'verifyCertificateQR' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CertificateVerification)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };