/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AIStep {
    completedAt?: Timestamp;
    model: string;
    output?: string;
    step: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QuizQuestion {
    id: bigint;
    question: string;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export interface QuizPublic {
    id: QuizId;
    lessonId: LessonId;
    passingScore: bigint;
    questions: Array<QuizQuestion>;
    courseId: CourseId;
}
export interface LibrarySearchResult {
    id: string;
    url: string;
    title: string;
    source: string;
    previewUrl?: string;
    year?: string;
    description: string;
    author: string;
    coverUrl?: string;
}
export interface ResourcePublic {
    id: bigint;
    status: ResourceStatus;
    title: string;
    subjects?: Array<string>;
    description: string;
    extractedText?: string;
    keywords?: Array<string>;
    resourceType: ResourceType;
    externalUrl?: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
    fileUrl?: string;
}
export interface AIModelConfig {
    validationModel: string;
    structureModel: string;
    contentModel: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface QuizAttempt {
    answers: Array<bigint>;
    score: bigint;
    attemptedAt: Timestamp;
    passed: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface EnrollmentPublic {
    completedAt?: Timestamp;
    lastLessonId?: LessonId;
    lessonProgress: Array<LessonProgressPublic>;
    learnerId: UserId;
    completionPercent: bigint;
    enrolledAt: Timestamp;
    courseId: CourseId;
}
export type CourseId = bigint;
export interface CourseGenerationPublic {
    id: bigint;
    status: GenerationStatus;
    aiModelConfig: AIModelConfig;
    requestDescription: string;
    libraryResultsCount: bigint;
    createdAt: Timestamp;
    errorMessage?: string;
    generatedCourseId?: CourseId;
    updatedAt: Timestamp;
    steps: Array<AIStep>;
    resourceIds: Array<bigint>;
    requestedBy: UserId;
}
export interface LessonProgressPublic {
    lessonId: LessonId;
    completed: boolean;
    quizAttempts: Array<QuizAttempt>;
    lastViewedAt: Timestamp;
}
export interface CoursePublic {
    id: CourseId;
    title: string;
    thumbnail?: ExternalBlob;
    isPublished: boolean;
    difficulty: Difficulty;
    createdAt: Timestamp;
    description: string;
    instructorId: UserId;
    updatedAt: Timestamp;
    learningOutcomes: Array<string>;
    category: string;
}
export type LessonId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LessonInput {
    title: string;
    content: string;
    videoBlob?: ExternalBlob;
    lessonType: LessonType;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface QuizResult {
    score: bigint;
    totalQuestions: bigint;
    correctAnswers: bigint;
    passed: boolean;
}
export interface LessonPublic {
    id: LessonId;
    title: string;
    content: string;
    hasQuiz: boolean;
    order: bigint;
    createdAt: Timestamp;
    videoBlob?: ExternalBlob;
    lessonType: LessonType;
    courseId: CourseId;
}
export interface QuizSubmission {
    answers: Array<bigint>;
    quizId: QuizId;
}
export interface UserProfilePublic {
    id: UserId;
    bio: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ExternalCoursePublic {
    id: string;
    url: string;
    title: string;
    thumbnailUrl?: string;
    description: string;
    platform: string;
    viewCount: bigint;
    addedAt: Timestamp;
    addedBy: UserId;
}
export interface CourseInput {
    title: string;
    thumbnail?: ExternalBlob;
    difficulty: Difficulty;
    description: string;
    learningOutcomes: Array<string>;
    category: string;
}
export type CertificateId = string;
export interface LibrarySearchQuery {
    domain?: string;
    profession?: string;
    searchTerm: string;
    maxResults: bigint;
}
export interface CertificateVerification {
    issueDate: Timestamp;
    courseTitle: string;
    isValid: boolean;
    ministryApproved: boolean;
}
export interface Certificate {
    id: CertificateId;
    ministryReviewerName?: string;
    approvedAt?: Timestamp;
    isMinistryApproved: boolean;
    resourceCitations: Array<string>;
    learnerId: UserId;
    learnerName: string;
    issuedAt: Timestamp;
    courseTitle: string;
    qrCodePayload: string;
    courseId: CourseId;
    instructorName: string;
}
export type QuizId = bigint;
export enum Difficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum GenerationStatus {
    step3_gpt4o = "step3_gpt4o",
    step1_deepseek = "step1_deepseek",
    approved = "approved",
    rejected = "rejected",
    step2_qwen = "step2_qwen",
    queued = "queued",
    revision_needed = "revision_needed"
}
export enum LessonType {
    video = "video",
    text = "text"
}
export enum ResourceStatus {
    pending = "pending",
    error = "error",
    indexed = "indexed"
}
export enum ResourceType {
    pdf = "pdf",
    video = "video",
    html = "html",
    word = "word",
    weblink = "weblink",
    excel = "excel",
    library_book = "library_book",
    youtube = "youtube",
    external_course = "external_course"
}
export enum UserRole {
    ministryReviewer = "ministryReviewer",
    learner = "learner",
    admin = "admin",
    instructor = "instructor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addExternalCourse(url: string, title: string, description: string, platform: string, thumbnailUrl: string | null): Promise<{
        __kind__: "ok";
        ok: ExternalCoursePublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addLesson(courseId: CourseId, input: LessonInput): Promise<LessonId>;
    approveGeneratedCourse(generationId: bigint, reviewerNotes: string): Promise<CourseGenerationPublic>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createCourse(input: CourseInput): Promise<CourseId>;
    deleteCourse(courseId: CourseId): Promise<void>;
    deleteExternalCourse(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteLesson(lessonId: LessonId): Promise<void>;
    deleteQuiz(lessonId: LessonId): Promise<void>;
    deleteResource(id: bigint): Promise<void>;
    enrollCourse(courseId: CourseId): Promise<void>;
    getAdminModelConfig(): Promise<AIModelConfig>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCertificate(certId: CertificateId): Promise<Certificate | null>;
    getCourse(courseId: CourseId): Promise<CoursePublic | null>;
    getCourseEnrollments(courseId: CourseId): Promise<Array<EnrollmentPublic>>;
    getGenerationStatus(generationId: bigint): Promise<CourseGenerationPublic | null>;
    getInstructorCourses(): Promise<Array<CoursePublic>>;
    getLessons(courseId: CourseId): Promise<Array<LessonPublic>>;
    getMyCertificates(): Promise<Array<Certificate>>;
    getMyEnrollments(): Promise<Array<EnrollmentPublic>>;
    getQuiz(lessonId: LessonId): Promise<QuizPublic | null>;
    getResource(id: bigint): Promise<ResourcePublic | null>;
    getUserProfile(userId: UserId): Promise<UserProfilePublic | null>;
    indexResourceText(id: bigint, extractedText: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllGenerations(): Promise<Array<CourseGenerationPublic>>;
    listCourses(category: string | null): Promise<Array<CoursePublic>>;
    listExternalCourses(): Promise<Array<ExternalCoursePublic>>;
    listMyGenerations(): Promise<Array<CourseGenerationPublic>>;
    listResources(resourceType: ResourceType | null, search: string | null): Promise<Array<ResourcePublic>>;
    markLessonComplete(courseId: CourseId, lessonId: LessonId): Promise<void>;
    rejectGeneratedCourse(generationId: bigint, reason: string): Promise<CourseGenerationPublic>;
    reorderLesson(lessonId: LessonId, newOrder: bigint): Promise<void>;
    requestCourseGeneration(description: string, resourceIds: Array<bigint> | null): Promise<CourseGenerationPublic>;
    runAIGeneration(generationId: bigint): Promise<void>;
    saveCallerUserProfile(name: string, bio: string, role: UserRole): Promise<void>;
    saveLastViewedLesson(courseId: CourseId, lessonId: LessonId): Promise<void>;
    searchCourses(searchTerm: string, category: string | null): Promise<Array<CoursePublic>>;
    searchWorldLibraries(searchQuery: LibrarySearchQuery): Promise<Array<LibrarySearchResult>>;
    setAdminModelConfig(config: AIModelConfig): Promise<void>;
    setCoursePublished(courseId: CourseId, published: boolean): Promise<void>;
    setQuiz(lessonId: LessonId, questions: Array<QuizQuestion>, passingScore: bigint): Promise<QuizId>;
    submitQuiz(courseId: CourseId, submission: QuizSubmission): Promise<QuizResult>;
    trackExternalCourseView(id: string): Promise<void>;
    transformHttpResponse(input: TransformationInput): Promise<TransformationOutput>;
    unenrollCourse(courseId: CourseId): Promise<void>;
    updateCourse(courseId: CourseId, input: CourseInput): Promise<void>;
    updateLesson(lessonId: LessonId, input: LessonInput): Promise<void>;
    updateResourceMetadata(id: bigint, title: string, description: string, keywords: Array<string> | null, subjects: Array<string> | null): Promise<ResourcePublic>;
    uploadResource(title: string, description: string, resourceType: ResourceType, fileUrl: string | null, externalUrl: string | null, keywords: Array<string> | null): Promise<ResourcePublic>;
    verifyCertificateQR(qrPayload: string): Promise<CertificateVerification | null>;
}
import type { AIModelConfig as _AIModelConfig, AIStep as _AIStep, Certificate as _Certificate, CertificateId as _CertificateId, CertificateVerification as _CertificateVerification, CourseGenerationPublic as _CourseGenerationPublic, CourseId as _CourseId, CourseInput as _CourseInput, CoursePublic as _CoursePublic, Difficulty as _Difficulty, EnrollmentPublic as _EnrollmentPublic, ExternalBlob as _ExternalBlob, ExternalCoursePublic as _ExternalCoursePublic, GenerationStatus as _GenerationStatus, LessonId as _LessonId, LessonInput as _LessonInput, LessonProgressPublic as _LessonProgressPublic, LessonPublic as _LessonPublic, LessonType as _LessonType, LibrarySearchQuery as _LibrarySearchQuery, LibrarySearchResult as _LibrarySearchResult, QuizPublic as _QuizPublic, ResourcePublic as _ResourcePublic, ResourceStatus as _ResourceStatus, ResourceType as _ResourceType, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, UserRole__1 as _UserRole__1, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addExternalCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<{
        __kind__: "ok";
        ok: ExternalCoursePublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addExternalCourse(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExternalCourse(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLesson(arg0: CourseId, arg1: LessonInput): Promise<LessonId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(arg0, await to_candid_LessonInput_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(arg0, await to_candid_LessonInput_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async approveGeneratedCourse(arg0: bigint, arg1: string): Promise<CourseGenerationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.approveGeneratedCourse(arg0, arg1);
                return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveGeneratedCourse(arg0, arg1);
            return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: CourseInput): Promise<CourseId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(await to_candid_CourseInput_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(await to_candid_CourseInput_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteExternalCourse(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExternalCourse(arg0);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExternalCourse(arg0);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLesson(arg0: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async deleteResource(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async enrollCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollCourse(arg0);
            return result;
        }
    }
    async getAdminModelConfig(): Promise<AIModelConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminModelConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminModelConfig();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificate(arg0: CertificateId): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificate(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificate(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: CourseId): Promise<CoursePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseEnrollments(arg0: CourseId): Promise<Array<EnrollmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseEnrollments(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseEnrollments(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGenerationStatus(arg0: bigint): Promise<CourseGenerationPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenerationStatus(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenerationStatus(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstructorCourses(): Promise<Array<CoursePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstructorCourses();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstructorCourses();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessons(arg0: CourseId): Promise<Array<LessonPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCertificates();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCertificates();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEnrollments(): Promise<Array<EnrollmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: LessonId): Promise<QuizPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResource(arg0: bigint): Promise<ResourcePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async indexResourceText(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.indexResourceText(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.indexResourceText(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllGenerations(): Promise<Array<CourseGenerationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllGenerations();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllGenerations();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCourses(arg0: string | null): Promise<Array<CoursePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExternalCourses(): Promise<Array<ExternalCoursePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExternalCourses();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExternalCourses();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyGenerations(): Promise<Array<CourseGenerationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyGenerations();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyGenerations();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResources(arg0: ResourceType | null, arg1: string | null): Promise<Array<ResourcePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResources(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResources(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async markLessonComplete(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async rejectGeneratedCourse(arg0: bigint, arg1: string): Promise<CourseGenerationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectGeneratedCourse(arg0, arg1);
                return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectGeneratedCourse(arg0, arg1);
            return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderLesson(arg0: LessonId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderLesson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderLesson(arg0, arg1);
            return result;
        }
    }
    async requestCourseGeneration(arg0: string, arg1: Array<bigint> | null): Promise<CourseGenerationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.requestCourseGeneration(arg0, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestCourseGeneration(arg0, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CourseGenerationPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async runAIGeneration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAIGeneration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAIGeneration(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_UserRole_n79(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_UserRole_n79(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveLastViewedLesson(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLastViewedLesson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLastViewedLesson(arg0, arg1);
            return result;
        }
    }
    async searchCourses(arg0: string, arg1: string | null): Promise<Array<CoursePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCourses(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCourses(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchWorldLibraries(arg0: LibrarySearchQuery): Promise<Array<LibrarySearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchWorldLibraries(to_candid_LibrarySearchQuery_n81(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchWorldLibraries(to_candid_LibrarySearchQuery_n81(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminModelConfig(arg0: AIModelConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminModelConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminModelConfig(arg0);
            return result;
        }
    }
    async setCoursePublished(arg0: CourseId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoursePublished(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoursePublished(arg0, arg1);
            return result;
        }
    }
    async setQuiz(arg0: LessonId, arg1: Array<QuizQuestion>, arg2: bigint): Promise<QuizId> {
        if (this.processError) {
            try {
                const result = await this.actor.setQuiz(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setQuiz(arg0, arg1, arg2);
            return result;
        }
    }
    async submitQuiz(arg0: CourseId, arg1: QuizSubmission): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0, arg1);
            return result;
        }
    }
    async trackExternalCourseView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackExternalCourseView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackExternalCourseView(arg0);
            return result;
        }
    }
    async transformHttpResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async unenrollCourse(arg0: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollCourse(arg0);
            return result;
        }
    }
    async updateCourse(arg0: CourseId, arg1: CourseInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, await to_candid_CourseInput_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, await to_candid_CourseInput_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLesson(arg0: LessonId, arg1: LessonInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, await to_candid_LessonInput_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, await to_candid_LessonInput_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateResourceMetadata(arg0: bigint, arg1: string, arg2: string, arg3: Array<string> | null, arg4: Array<string> | null): Promise<ResourcePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResourceMetadata(arg0, arg1, arg2, to_candid_opt_n86(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg4));
                return from_candid_ResourcePublic_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResourceMetadata(arg0, arg1, arg2, to_candid_opt_n86(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg4));
            return from_candid_ResourcePublic_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadResource(arg0: string, arg1: string, arg2: ResourceType, arg3: string | null, arg4: string | null, arg5: Array<string> | null): Promise<ResourcePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadResource(arg0, arg1, to_candid_ResourceType_n75(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg5));
                return from_candid_ResourcePublic_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadResource(arg0, arg1, to_candid_ResourceType_n75(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg5));
            return from_candid_ResourcePublic_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyCertificateQR(arg0: string): Promise<CertificateVerification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCertificateQR(arg0);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCertificateQR(arg0);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AIStep_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIStep): AIStep {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Certificate_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certificate): Certificate {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_CourseGenerationPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseGenerationPublic): CourseGenerationPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_CoursePublic_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoursePublic): Promise<CoursePublic> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollmentPublic_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollmentPublic): EnrollmentPublic {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ExternalCoursePublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalCoursePublic): ExternalCoursePublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_GenerationStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenerationStatus): GenerationStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_LessonPublic_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonPublic): Promise<LessonPublic> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_LessonType_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonType): LessonType {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_LibrarySearchResult_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LibrarySearchResult): LibrarySearchResult {
    return from_candid_record_n85(_uploadFile, _downloadFile, value);
}
function from_candid_ResourcePublic_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourcePublic): ResourcePublic {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceStatus): ResourceStatus {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseId]): CourseId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : from_candid_Certificate_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoursePublic]): Promise<CoursePublic | null> {
    return value.length === 0 ? null : await from_candid_CoursePublic_n45(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonId]): LessonId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseGenerationPublic]): CourseGenerationPublic | null {
    return value.length === 0 ? null : from_candid_CourseGenerationPublic_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizPublic]): QuizPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResourcePublic]): ResourcePublic | null {
    return value.length === 0 ? null : from_candid_ResourcePublic_n65(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CertificateVerification]): CertificateVerification | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    thumbnailUrl: [] | [string];
    description: string;
    platform: string;
    viewCount: bigint;
    addedAt: _Timestamp;
    addedBy: _UserId;
}): {
    id: string;
    url: string;
    title: string;
    thumbnailUrl?: string;
    description: string;
    platform: string;
    viewCount: bigint;
    addedAt: Timestamp;
    addedBy: UserId;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.thumbnailUrl)),
        description: value.description,
        platform: value.platform,
        viewCount: value.viewCount,
        addedAt: value.addedAt,
        addedBy: value.addedBy
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GenerationStatus;
    aiModelConfig: _AIModelConfig;
    requestDescription: string;
    libraryResultsCount: bigint;
    createdAt: _Timestamp;
    errorMessage: [] | [string];
    generatedCourseId: [] | [_CourseId];
    updatedAt: _Timestamp;
    steps: Array<_AIStep>;
    resourceIds: Array<bigint>;
    requestedBy: _UserId;
}): {
    id: bigint;
    status: GenerationStatus;
    aiModelConfig: AIModelConfig;
    requestDescription: string;
    libraryResultsCount: bigint;
    createdAt: Timestamp;
    errorMessage?: string;
    generatedCourseId?: CourseId;
    updatedAt: Timestamp;
    steps: Array<AIStep>;
    resourceIds: Array<bigint>;
    requestedBy: UserId;
} {
    return {
        id: value.id,
        status: from_candid_GenerationStatus_n20(_uploadFile, _downloadFile, value.status),
        aiModelConfig: value.aiModelConfig,
        requestDescription: value.requestDescription,
        libraryResultsCount: value.libraryResultsCount,
        createdAt: value.createdAt,
        errorMessage: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.errorMessage)),
        generatedCourseId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.generatedCourseId)),
        updatedAt: value.updatedAt,
        steps: from_candid_vec_n23(_uploadFile, _downloadFile, value.steps),
        resourceIds: value.resourceIds,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Timestamp];
    model: string;
    output: [] | [string];
    step: bigint;
}): {
    completedAt?: Timestamp;
    model: string;
    output?: string;
    step: bigint;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.completedAt)),
        model: value.model,
        output: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.output)),
        step: value.step
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
}): {
    id: UserId;
    bio: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n37(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CertificateId;
    ministryReviewerName: [] | [string];
    approvedAt: [] | [_Timestamp];
    isMinistryApproved: boolean;
    resourceCitations: Array<string>;
    learnerId: _UserId;
    learnerName: string;
    issuedAt: _Timestamp;
    courseTitle: string;
    qrCodePayload: string;
    courseId: _CourseId;
    instructorName: string;
}): {
    id: CertificateId;
    ministryReviewerName?: string;
    approvedAt?: Timestamp;
    isMinistryApproved: boolean;
    resourceCitations: Array<string>;
    learnerId: UserId;
    learnerName: string;
    issuedAt: Timestamp;
    courseTitle: string;
    qrCodePayload: string;
    courseId: CourseId;
    instructorName: string;
} {
    return {
        id: value.id,
        ministryReviewerName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.ministryReviewerName)),
        approvedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.approvedAt)),
        isMinistryApproved: value.isMinistryApproved,
        resourceCitations: value.resourceCitations,
        learnerId: value.learnerId,
        learnerName: value.learnerName,
        issuedAt: value.issuedAt,
        courseTitle: value.courseTitle,
        qrCodePayload: value.qrCodePayload,
        courseId: value.courseId,
        instructorName: value.instructorName
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CourseId;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    isPublished: boolean;
    difficulty: _Difficulty;
    createdAt: _Timestamp;
    description: string;
    instructorId: _UserId;
    updatedAt: _Timestamp;
    learningOutcomes: Array<string>;
    category: string;
}): Promise<{
    id: CourseId;
    title: string;
    thumbnail?: ExternalBlob;
    isPublished: boolean;
    difficulty: Difficulty;
    createdAt: Timestamp;
    description: string;
    instructorId: UserId;
    updatedAt: Timestamp;
    learningOutcomes: Array<string>;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.thumbnail)),
        isPublished: value.isPublished,
        difficulty: from_candid_Difficulty_n49(_uploadFile, _downloadFile, value.difficulty),
        createdAt: value.createdAt,
        description: value.description,
        instructorId: value.instructorId,
        updatedAt: value.updatedAt,
        learningOutcomes: value.learningOutcomes,
        category: value.category
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Timestamp];
    lastLessonId: [] | [_LessonId];
    lessonProgress: Array<_LessonProgressPublic>;
    learnerId: _UserId;
    completionPercent: bigint;
    enrolledAt: _Timestamp;
    courseId: _CourseId;
}): {
    completedAt?: Timestamp;
    lastLessonId?: LessonId;
    lessonProgress: Array<LessonProgressPublic>;
    learnerId: UserId;
    completionPercent: bigint;
    enrolledAt: Timestamp;
    courseId: CourseId;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.completedAt)),
        lastLessonId: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.lastLessonId)),
        lessonProgress: value.lessonProgress,
        learnerId: value.learnerId,
        completionPercent: value.completionPercent,
        enrolledAt: value.enrolledAt,
        courseId: value.courseId
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LessonId;
    title: string;
    content: string;
    hasQuiz: boolean;
    order: bigint;
    createdAt: _Timestamp;
    videoBlob: [] | [_ExternalBlob];
    lessonType: _LessonType;
    courseId: _CourseId;
}): Promise<{
    id: LessonId;
    title: string;
    content: string;
    hasQuiz: boolean;
    order: bigint;
    createdAt: Timestamp;
    videoBlob?: ExternalBlob;
    lessonType: LessonType;
    courseId: CourseId;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        hasQuiz: value.hasQuiz,
        order: value.order,
        createdAt: value.createdAt,
        videoBlob: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.videoBlob)),
        lessonType: from_candid_LessonType_n60(_uploadFile, _downloadFile, value.lessonType),
        courseId: value.courseId
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ResourceStatus;
    title: string;
    subjects: [] | [Array<string>];
    description: string;
    extractedText: [] | [string];
    keywords: [] | [Array<string>];
    resourceType: _ResourceType;
    externalUrl: [] | [string];
    uploadedAt: _Timestamp;
    uploadedBy: _UserId;
    fileUrl: [] | [string];
}): {
    id: bigint;
    status: ResourceStatus;
    title: string;
    subjects?: Array<string>;
    description: string;
    extractedText?: string;
    keywords?: Array<string>;
    resourceType: ResourceType;
    externalUrl?: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
    fileUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_ResourceStatus_n67(_uploadFile, _downloadFile, value.status),
        title: value.title,
        subjects: record_opt_to_undefined(from_candid_opt_n69(_uploadFile, _downloadFile, value.subjects)),
        description: value.description,
        extractedText: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.extractedText)),
        keywords: record_opt_to_undefined(from_candid_opt_n69(_uploadFile, _downloadFile, value.keywords)),
        resourceType: from_candid_ResourceType_n70(_uploadFile, _downloadFile, value.resourceType),
        externalUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.externalUrl)),
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy,
        fileUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.fileUrl))
    };
}
function from_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    source: string;
    previewUrl: [] | [string];
    year: [] | [string];
    description: string;
    author: string;
    coverUrl: [] | [string];
}): {
    id: string;
    url: string;
    title: string;
    source: string;
    previewUrl?: string;
    year?: string;
    description: string;
    author: string;
    coverUrl?: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        source: value.source,
        previewUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.previewUrl)),
        year: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.year)),
        description: value.description,
        author: value.author,
        coverUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.coverUrl))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step3_gpt4o: null;
} | {
    step1_deepseek: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    step2_qwen: null;
} | {
    queued: null;
} | {
    revision_needed: null;
}): GenerationStatus {
    return "step3_gpt4o" in value ? GenerationStatus.step3_gpt4o : "step1_deepseek" in value ? GenerationStatus.step1_deepseek : "approved" in value ? GenerationStatus.approved : "rejected" in value ? GenerationStatus.rejected : "step2_qwen" in value ? GenerationStatus.step2_qwen : "queued" in value ? GenerationStatus.queued : "revision_needed" in value ? GenerationStatus.revision_needed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ministryReviewer: null;
} | {
    learner: null;
} | {
    admin: null;
} | {
    instructor: null;
}): UserRole {
    return "ministryReviewer" in value ? UserRole.ministryReviewer : "learner" in value ? UserRole.learner : "admin" in value ? UserRole.admin : "instructor" in value ? UserRole.instructor : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): Difficulty {
    return "intermediate" in value ? Difficulty.intermediate : "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    text: null;
}): LessonType {
    return "video" in value ? LessonType.video : "text" in value ? LessonType.text : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    error: null;
} | {
    indexed: null;
}): ResourceStatus {
    return "pending" in value ? ResourceStatus.pending : "error" in value ? ResourceStatus.error : "indexed" in value ? ResourceStatus.indexed : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    video: null;
} | {
    html: null;
} | {
    word: null;
} | {
    weblink: null;
} | {
    excel: null;
} | {
    library_book: null;
} | {
    youtube: null;
} | {
    external_course: null;
}): ResourceType {
    return "pdf" in value ? ResourceType.pdf : "video" in value ? ResourceType.video : "html" in value ? ResourceType.html : "word" in value ? ResourceType.word : "weblink" in value ? ResourceType.weblink : "excel" in value ? ResourceType.excel : "library_book" in value ? ResourceType.library_book : "youtube" in value ? ResourceType.youtube : "external_course" in value ? ResourceType.external_course : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ExternalCoursePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ExternalCoursePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ExternalCoursePublic_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AIStep>): Array<AIStep> {
    return value.map((x)=>from_candid_AIStep_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EnrollmentPublic>): Array<EnrollmentPublic> {
    return value.map((x)=>from_candid_EnrollmentPublic_n52(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoursePublic>): Promise<Array<CoursePublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CoursePublic_n45(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LessonPublic>): Promise<Array<LessonPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LessonPublic_n58(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Certificate>): Array<Certificate> {
    return value.map((x)=>from_candid_Certificate_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseGenerationPublic>): Array<CourseGenerationPublic> {
    return value.map((x)=>from_candid_CourseGenerationPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalCoursePublic>): Array<ExternalCoursePublic> {
    return value.map((x)=>from_candid_ExternalCoursePublic_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResourcePublic>): Array<ResourcePublic> {
    return value.map((x)=>from_candid_ResourcePublic_n65(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LibrarySearchResult>): Array<LibrarySearchResult> {
    return value.map((x)=>from_candid_LibrarySearchResult_n84(_uploadFile, _downloadFile, x));
}
async function to_candid_CourseInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseInput): Promise<_CourseInput> {
    return await to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_LessonInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonInput): Promise<_LessonInput> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_LessonType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): _LessonType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_LibrarySearchQuery_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LibrarySearchQuery): _LibrarySearchQuery {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceType_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): _ResourceType {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType | null): [] | [_ResourceType] {
    return value === null ? candid_none() : candid_some(to_candid_ResourceType_n75(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<bigint> | null): [] | [Array<bigint>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    videoBlob?: ExternalBlob;
    lessonType: LessonType;
}): Promise<{
    title: string;
    content: string;
    videoBlob: [] | [_ExternalBlob];
    lessonType: _LessonType;
}> {
    return {
        title: value.title,
        content: value.content,
        videoBlob: value.videoBlob ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.videoBlob)) : candid_none(),
        lessonType: to_candid_LessonType_n16(_uploadFile, _downloadFile, value.lessonType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnail?: ExternalBlob;
    difficulty: Difficulty;
    description: string;
    learningOutcomes: Array<string>;
    category: string;
}): Promise<{
    title: string;
    thumbnail: [] | [_ExternalBlob];
    difficulty: _Difficulty;
    description: string;
    learningOutcomes: Array<string>;
    category: string;
}> {
    return {
        title: value.title,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        difficulty: to_candid_Difficulty_n31(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        learningOutcomes: value.learningOutcomes,
        category: value.category
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domain?: string;
    profession?: string;
    searchTerm: string;
    maxResults: bigint;
}): {
    domain: [] | [string];
    profession: [] | [string];
    searchTerm: string;
    maxResults: bigint;
} {
    return {
        domain: value.domain ? candid_some(value.domain) : candid_none(),
        profession: value.profession ? candid_some(value.profession) : candid_none(),
        searchTerm: value.searchTerm,
        maxResults: value.maxResults
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): {
    video: null;
} | {
    text: null;
} {
    return value == LessonType.video ? {
        video: null
    } : value == LessonType.text ? {
        text: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == Difficulty.intermediate ? {
        intermediate: null
    } : value == Difficulty.beginner ? {
        beginner: null
    } : value == Difficulty.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceType): {
    pdf: null;
} | {
    video: null;
} | {
    html: null;
} | {
    word: null;
} | {
    weblink: null;
} | {
    excel: null;
} | {
    library_book: null;
} | {
    youtube: null;
} | {
    external_course: null;
} {
    return value == ResourceType.pdf ? {
        pdf: null
    } : value == ResourceType.video ? {
        video: null
    } : value == ResourceType.html ? {
        html: null
    } : value == ResourceType.word ? {
        word: null
    } : value == ResourceType.weblink ? {
        weblink: null
    } : value == ResourceType.excel ? {
        excel: null
    } : value == ResourceType.library_book ? {
        library_book: null
    } : value == ResourceType.youtube ? {
        youtube: null
    } : value == ResourceType.external_course ? {
        external_course: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    ministryReviewer: null;
} | {
    learner: null;
} | {
    admin: null;
} | {
    instructor: null;
} {
    return value == UserRole.ministryReviewer ? {
        ministryReviewer: null
    } : value == UserRole.learner ? {
        learner: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.instructor ? {
        instructor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
